"""
Krakken AI — Speech Integration.

Connects assistant responses to the speech subsystem.

Architecture:

    Assistant
        ↓
    SpeechIntegration
        ↓
    SpeechBridge
        ↓
    SpeechController
        ↓
    TTSWorker
        ↓
    Kokoro
        ↓
    SpeechQueue
        ↓
    AudioPlayer
        ↓
    Speakers

This module does NOT know about:

- Kokoro
- TTS models
- audio devices
- audio playback
- speech queues
- TTS workers

It only connects assistant output to SpeechBridge.
"""

from __future__ import annotations

from typing import Any, Optional

from core.voice.speech_bridge import SpeechBridge


class SpeechIntegration:
    """
    Connects the assistant response pipeline to speech output.
    """

    def __init__(
        self,
        speech_bridge: SpeechBridge,
        logger: Any = None,
        enabled: bool = True,
    ) -> None:

        if speech_bridge is None:
            raise ValueError(
                "speech_bridge cannot be None."
            )

        self._speech_bridge = speech_bridge
        self._logger = logger
        self._enabled = enabled

        self._log(
            "SpeechIntegration created."
        )

    # ==================================================
    # HANDLE RESPONSE
    # ==================================================

    def handle_response(
        self,
        response: str,
    ) -> Optional[int]:
        """
        Forward an assistant response to speech.

        Args:
            response:
                Final text generated by the assistant.

        Returns:
            Speech sequence number if accepted,
            otherwise None.
        """

        if not self._enabled:
            self._log(
                "SpeechIntegration is disabled."
            )
            return None

        if not response or not response.strip():
            self._log(
                "Ignoring empty assistant response."
            )
            return None

        response = response.strip()

        self._log(
            f"Handling assistant response: "
            f"{response[:100]!r}"
        )

        try:

            sequence = self._speech_bridge.speak(
                response
            )

            self._log(
                f"Assistant response sent to speech. "
                f"Sequence: {sequence}"
            )

            return sequence

        except Exception as exc:

            self._log(
                f"Failed to send assistant response "
                f"to speech: {exc}",
                error=True,
            )

            raise

    # ==================================================
    # ENABLE / DISABLE
    # ==================================================

    def enable(self) -> None:
        """
        Enable speech integration.
        """

        self._enabled = True

        self._speech_bridge.enable()

        self._log(
            "SpeechIntegration enabled."
        )

    def disable(
        self,
        *,
        stop_current: bool = True,
    ) -> None:
        """
        Disable speech integration.

        Args:
            stop_current:
                Stop currently playing speech when disabled.
        """

        self._enabled = False

        self._speech_bridge.disable(
            stop_current=stop_current
        )

        self._log(
            "SpeechIntegration disabled."
        )

    @property
    def enabled(self) -> bool:
        """
        Return whether speech integration is enabled.
        """

        return self._enabled

    # ==================================================
    # STATUS
    # ==================================================

    @property
    def is_speaking(self) -> bool:
        """
        Return whether Krakken is currently speaking.
        """

        return self._speech_bridge.is_speaking

    @property
    def pending(self) -> int:
        """
        Return the number of pending speech requests.
        """

        return self._speech_bridge.pending

    # ==================================================
    # STOP
    # ==================================================

    def stop(self) -> None:
        """
        Stop current speech playback.
        """

        self._log(
            "Stopping speech integration."
        )

        self._speech_bridge.stop()

    # ==================================================
    # SHUTDOWN
    # ==================================================

    def shutdown(self) -> None:
        """
        Shut down the speech integration layer.
        """

        self._log(
            "Shutting down SpeechIntegration..."
        )

        try:

            self._speech_bridge.shutdown()

        finally:

            self._enabled = False

        self._log(
            "SpeechIntegration shutdown complete."
        )

    # ==================================================
    # LOGGING
    # ==================================================

    def _log(
        self,
        message: str,
        error: bool = False,
    ) -> None:
        """
        Safely write to Krakken's logger.
        """

        if self._logger is None:
            return

        try:

            if error:

                self._logger.error(
                    message
                )

            else:

                self._logger.info(
                    message
                )

        except Exception:
            pass