"""
Krakken AI - Text-to-Speech Provider Abstraction.

Defines the common interface used by all TTS engines.

The rest of Krakken should never need to know whether
speech is generated by Kokoro, another local model, or
a future remote provider.
"""

from __future__ import annotations

from abc import ABC, abstractmethod
from dataclasses import dataclass

import numpy as np


@dataclass(frozen=True)
class AudioData:
    """
    Audio produced by a TTS provider.

    Attributes:
        samples:
            Audio samples as a NumPy array or raw PCM bytes.

        sample_rate:
            Audio sample rate in Hz.

        channels:
            Number of audio channels.

        sample_width:
            Bytes per sample when using raw PCM bytes.
    """

    samples: bytes | bytearray | memoryview | np.ndarray

    sample_rate: int

    channels: int = 1

    sample_width: int = 2


class TTSProvider(ABC):
    """
    Abstract interface for text-to-speech providers.
    """

    @abstractmethod
    def initialize(self) -> None:
        """
        Initialize the TTS engine.

        Heavy model loading should happen here rather than
        during every synthesis request.
        """
        raise NotImplementedError

    @abstractmethod
    def synthesize(
        self,
        text: str,
    ) -> AudioData:
        """
        Convert text into audio.

        Args:
            text:
                Text to synthesize.

        Returns:
            AudioData containing generated audio.
        """
        raise NotImplementedError

    @abstractmethod
    def shutdown(self) -> None:
        """
        Release model resources.
        """
        raise NotImplementedError

    @property
    @abstractmethod
    def is_initialized(self) -> bool:
        """
        Whether the provider is ready for synthesis.
        """
        raise NotImplementedError