"""
Krakken AI — Assistant Response Handler.

Responsible for handling finalized assistant responses.

Architecture:

    Assistant / LLM
          ↓
    ResponseHandler
       ↙       ↘
 Display/UI   SpeechIntegration
                  ↓
             SpeechBridge
                  ↓
          SpeechController
                  ↓
                TTS

The ResponseHandler intentionally knows nothing about:

- Kokoro
- TTS models
- audio devices
- audio playback
- speech queues
- TTS workers

It only coordinates what should happen with a finalized
assistant response.
"""

from __future__ import annotations

from typing import Any, Optional

from core.voice.speech_integration import SpeechIntegration


class ResponseHandler:
    """
    Handles finalized responses produced by the assistant.

    The handler acts as the boundary between the assistant
    brain and output systems such as speech.
    """

    def __init__(
        self,
        speech_integration: Optional[SpeechIntegration] = None,
        logger: Any = None,
        speech_enabled: bool = True,
    ) -> None:

        self._speech_integration = speech_integration
        self._logger = logger
        self._speech_enabled = speech_enabled

        self._log(
            "ResponseHandler created."
        )

    # ==================================================
    # HANDLE RESPONSE
    # ==================================================

    def handle(
        self,
        response: str,
    ) -> Optional[int]:
        """
        Handle a finalized assistant response.

        Args:
            response:
                Final response generated by the assistant.

        Returns:
            Speech sequence number when speech is accepted,
            otherwise None.
        """

        if not response or not response.strip():

            self._log(
                "Ignoring empty assistant response."
            )

            return None

        response = response.strip()

        self._log(
            f"Handling assistant response: "
            f"{response[:100]!r}"
        )

        speech_sequence: Optional[int] = None

        # --------------------------------------------------
        # SPEECH
        # --------------------------------------------------

        if (
            self._speech_enabled
            and self._speech_integration is not None
        ):

            try:

                speech_sequence = (
                    self._speech_integration.handle_response(
                        response
                    )
                )

                self._log(
                    "Assistant response forwarded "
                    f"to speech. Sequence: "
                    f"{speech_sequence}"
                )

            except Exception as exc:

                self._log(
                    f"Failed to forward response "
                    f"to speech: {exc}",
                    error=True,
                )

                raise

        else:

            self._log(
                "Speech output skipped."
            )

        return speech_sequence

    # ==================================================
    # SPEECH CONTROL
    # ==================================================

    def enable_speech(self) -> None:
        """
        Enable speech output for assistant responses.
        """

        self._speech_enabled = True

        if self._speech_integration is not None:

            self._speech_integration.enable()

        self._log(
            "Assistant speech enabled."
        )

    def disable_speech(
        self,
        *,
        stop_current: bool = True,
    ) -> None:
        """
        Disable speech output for assistant responses.

        Args:
            stop_current:
                Stop currently playing speech.
        """

        self._speech_enabled = False

        if self._speech_integration is not None:

            self._speech_integration.disable(
                stop_current=stop_current
            )

        self._log(
            "Assistant speech disabled."
        )

    @property
    def speech_enabled(self) -> bool:
        """
        Return whether assistant speech output is enabled.
        """

        return self._speech_enabled

    # ==================================================
    # STATUS
    # ==================================================

    @property
    def is_speaking(self) -> bool:
        """
        Return whether Krakken is currently speaking.
        """

        if self._speech_integration is None:
            return False

        return self._speech_integration.is_speaking

    @property
    def pending_speech(self) -> int:
        """
        Return the number of pending speech requests.
        """

        if self._speech_integration is None:
            return 0

        return self._speech_integration.pending

    # ==================================================
    # STOP
    # ==================================================

    def stop_speech(self) -> None:
        """
        Stop the current assistant speech.
        """

        if self._speech_integration is None:
            return

        self._log(
            "Stopping assistant speech."
        )

        self._speech_integration.stop()

    # ==================================================
    # SHUTDOWN
    # ==================================================

    def shutdown(self) -> None:
        """
        Shut down the speech output subsystem.
        """

        self._log(
            "Shutting down ResponseHandler..."
        )

        if self._speech_integration is not None:

            self._speech_integration.shutdown()

        self._speech_enabled = False

        self._log(
            "ResponseHandler shutdown complete."
        )

    # ==================================================
    # LOGGING
    # ==================================================

    def _log(
        self,
        message: str,
        error: bool = False,
    ) -> None:
        """
        Safely write to Krakken's logger.
        """

        if self._logger is None:
            return

        try:

            if error:

                self._logger.error(
                    message
                )

            else:

                self._logger.info(
                    message
                )

        except Exception:
            pass